repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args:
            [
                "--ini",
                ".bandit"
            ]
-   repo: local
    hooks:
    -   id: pylint
        rev: 2.14.5
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
            [
            "--rcfile=.pylintrc", # Link to your config file
            ]
