name: Linting and Running Tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - main
      - develop
      - 'release/**'
jobs:
  build:
    name: Linting and Running Test
    # Run older version of ubuntu due to Sample Tracker
    # https://askubuntu.com/questions/1231844/ssl-sslerror-ssl-dh-key-too-small-dh-key-too-small-ssl-c1108
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.9, 3.10]
    environment:
      name: TEST
    env:
      SAMPLE_TRACKER_TOKEN: ${{ secrets.SAMPLE_TRACKER_TOKEN }}
      SAMPLE_TRACKER_URL: ${{ secrets.SAMPLE_TRACKER_URL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[all]
      - name: Lint with pylint
        run: |
          pylint gift-wrap
      # - name: Test with pytest
      #   run: |
      #     pytest
